name: Report Coverage

on:
  pull_request:
    branches:
      - main

jobs:
  test:
    uses: ./.github/workflows/test.yml

  comment:
    name: Comment
    runs-on: ubuntu-latest
    needs: [test]

    permissions:
      # Required to checkout the code
      contents: read
      # Required to put a comment into the pull-request
      pull-requests: write

    steps:
      - name: 'Report Coverage'
        if: always()
        uses:  davelosert/vitest-coverage-report-action@v2
